spring:
  application:
    name: hometodo
  datasource:
    url: jdbc:sqlite:hometodo.db
    driver-class-name: org.sqlite.JDBC
  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8080
  address: 0.0.0.0

logging:
  file:
    name: hometodo.log
  level:
    root: DEBUG
    net.simnacher.hometodo: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n"
